// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg901.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fMsg901_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fMsg901_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fMsg901_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fMsg901_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fMsg901_2eproto;
class Msg901;
struct Msg901DefaultTypeInternal;
extern Msg901DefaultTypeInternal _Msg901_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Msg901* Arena::CreateMaybeMessage<::Msg901>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Msg901 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Msg901) */ {
 public:
  inline Msg901() : Msg901(nullptr) {}
  ~Msg901() override;
  explicit PROTOBUF_CONSTEXPR Msg901(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Msg901(const Msg901& from);
  Msg901(Msg901&& from) noexcept
    : Msg901() {
    *this = ::std::move(from);
  }

  inline Msg901& operator=(const Msg901& from) {
    CopyFrom(from);
    return *this;
  }
  inline Msg901& operator=(Msg901&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Msg901& default_instance() {
    return *internal_default_instance();
  }
  static inline const Msg901* internal_default_instance() {
    return reinterpret_cast<const Msg901*>(
               &_Msg901_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Msg901& a, Msg901& b) {
    a.Swap(&b);
  }
  inline void Swap(Msg901* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Msg901* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Msg901* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Msg901>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Msg901& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Msg901& from) {
    Msg901::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Msg901* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Msg901";
  }
  protected:
  explicit Msg901(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 3,
    kMsgIdFieldNumber = 1,
    kMachineIdFieldNumber = 2,
  };
  // string msg = 3;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // float msg_id = 1;
  void clear_msg_id();
  float msg_id() const;
  void set_msg_id(float value);
  private:
  float _internal_msg_id() const;
  void _internal_set_msg_id(float value);
  public:

  // int32 machine_id = 2;
  void clear_machine_id();
  int32_t machine_id() const;
  void set_machine_id(int32_t value);
  private:
  int32_t _internal_machine_id() const;
  void _internal_set_machine_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Msg901)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    float msg_id_;
    int32_t machine_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fMsg901_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Msg901

// float msg_id = 1;
inline void Msg901::clear_msg_id() {
  _impl_.msg_id_ = 0;
}
inline float Msg901::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline float Msg901::msg_id() const {
  // @@protoc_insertion_point(field_get:Msg901.msg_id)
  return _internal_msg_id();
}
inline void Msg901::_internal_set_msg_id(float value) {
  
  _impl_.msg_id_ = value;
}
inline void Msg901::set_msg_id(float value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:Msg901.msg_id)
}

// int32 machine_id = 2;
inline void Msg901::clear_machine_id() {
  _impl_.machine_id_ = 0;
}
inline int32_t Msg901::_internal_machine_id() const {
  return _impl_.machine_id_;
}
inline int32_t Msg901::machine_id() const {
  // @@protoc_insertion_point(field_get:Msg901.machine_id)
  return _internal_machine_id();
}
inline void Msg901::_internal_set_machine_id(int32_t value) {
  
  _impl_.machine_id_ = value;
}
inline void Msg901::set_machine_id(int32_t value) {
  _internal_set_machine_id(value);
  // @@protoc_insertion_point(field_set:Msg901.machine_id)
}

// string msg = 3;
inline void Msg901::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& Msg901::msg() const {
  // @@protoc_insertion_point(field_get:Msg901.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Msg901::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Msg901.msg)
}
inline std::string* Msg901::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:Msg901.msg)
  return _s;
}
inline const std::string& Msg901::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void Msg901::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* Msg901::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* Msg901::release_msg() {
  // @@protoc_insertion_point(field_release:Msg901.msg)
  return _impl_.msg_.Release();
}
inline void Msg901::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Msg901.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fMsg901_2eproto
